---
- name: "Start service Xpaste"
  ansible.builtin.systemd:
    state: "started"
    enabled: true
    daemon_reload: true
    name: "xpaste"

- name: "Restart service Nginx"
  ansible.builtin.systemd:
    state: "restarted"
    name: "nginx"
