---
- name: "Deploy of Xpaste application"
  hosts: "server"
  become: true
  vars:
    DB_HOST: "127.0.0.1"
    DB_PORT: "5432"
    DB_NAME: "testdb"
    DB_USER: "test"
    DB_PASSWORD: "test"
    RAILS_ENV: "production"
    RAILS_LOG_TO_STDOUT: "1"
    SECRET_KEY_BASE: "test"
    GIT_REPO: "gitlab.slurm.io/edu/xpaste_practicum.git"
    GIT_CREDENTIALS_USERNAME: ""
    GIT_CREDENTIALS_PASSWORD: ""
  roles:
  - role: postgresql
    postgresql_db_user: "{{ DB_USER }}"
    postgresql_db_pass: "{{ DB_PASSWORD }}"
    postgresql_db_name: "{{ DB_NAME }}"
  - role: nginxinc.nginx
    nginx_selinux_enforcing: false
  - role: xpaste
    xpaste_git_credentials_username: "{{ GIT_CREDENTIALS_USERNAME }}"
    xpaste_git_credentials_password: "{{ GIT_CREDENTIALS_PASSWORD }}"
    xpaste_git_https_repository: "{{ GIT_REPO }}"
    xpaste_secret_key_base: "{{ SECRET_KEY_BASE }}"
    xpaste_rails_env: "{{ RAILS_ENV }}"
    xpaste_rails_log_to_stdout: "{{ RAILS_LOG_TO_STDOUT }}"
    xpaste_db_host: "{{ DB_HOST }}"
    xpaste_db_port: "{{ DB_PORT }}"
    xpaste_db_name: "{{ DB_NAME }}"
    xpaste_db_user: "{{ DB_USER }}"
    xpaste_db_password: "{{ DB_PASSWORD }}"
